project_id = "xvgoogyagdbgphympzkg"

[functions.spotify-playlist]
verify_jwt = false

[functions.playlist-vibe]
verify_jwt = false

[functions.playlist-player]
verify_jwt = false

[functions.track-engagement]
verify_jwt = false
